version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--save', '', '--appendonly', 'no']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 20
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITHUB_API_BASE_URL=https://api.github.com
      - GITHUB_API_VERSION=2022-11-28
      - GITHUB_TIMEOUT_MS=5000
      - CACHE_SEARCH_TTL_MS=300000
    ports:
      - '3000:3000'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
